"""empty message

Revision ID: 858332fde851
Revises: c01d405ca8f8
Create Date: 2025-08-23 16:14:27.785690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '858332fde851'
down_revision = 'c01d405ca8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
